### ISSUE TITLE
!yolo task=segment mode=predict model=runs/segment/train/weights/best.pt source="test_data" didn't save the prediction results

### ISSUE THREAD

**Issue by Wong-denis** [AarohiSingla/YOLOv8-Image-Segmentation#1]
Thank you for your tutorial for yolov8 using custom dataset!
But I encountered few problem during the prediction step. I already managed to train my own dataset and get the model "runs/segment/train/weights/best.pt", so I run the command line below on my terminal
`yolo task=segment mode=predict model=runs/segment/train/weights/best.pt source="test_data"`
and here is the result i got
![Screenshot from 2023-02-13 17-35-45](https://user-images.githubusercontent.com/57944444/218422439-a924ffa1-0482-4bce-b3d9-33a336460175.png)
In your tutorial, there is this line "Results saved to **runs/segment/predict**"
but it didn't save the images for me. So I can't check my result

I follow the tutorial viedo the entire time, so I really don't know why this is happening 
Is there any problem with my command?
what can I do to save(or at least show) my results?

thanks in advanced

**Comment by Wong-denis** [comment]
[https://github.com/ultralytics/ultralytics/issues/375#issue-1533839128](url)

**Comment by AarohiSingla** [comment]
Use save=True in your command
